### PR TITLE
fix: missing icon, fixes #18, #16

### LINKED ISSUE #18: Crash in IDEA 2022.2.3
java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons
	at com.fapiko.jetbrains.plugins.better_direnv.language.filetype.DirenvFileType.getIcon(DirenvFileType.java:38)

Seems it needs adaption to the new IDEA version.

### PR DESCRIPTION
**Pull request by shyim**
- Updated Gradle
- Updated Intelij Plugin to latest version
- Changed Required version to latest 2022.3 versions
- Fixed icon name

Fixes issues #18 and #16

### CODE REVIEW

**Comment by toaster** [comment]
@shyim thank you for addressing this annoying issue.
It seems that @Fapiko hasn’t the time to release this, currently.
Could you provide a fixed version of the plugin for install from disk for adventurous people like me? :)

**Comment by ericfialkowski** [comment]
I second that request, if you have the time to do that.

**Comment by axaluss** [comment]
There you go
[better_direnv-1.0.0.zip](https://github.com/Fapiko/intellij-better-direnv/files/10461170/better_direnv-1.0.0.zip)

**Comment by toaster** [comment]
Thank you very much @axaluss!

**Comment by domenkozar** [comment]
@Fapiko could you help us out here? 🙏

**Review by Fapiko — APPROVED** [review]

**Comment by evgenii-rekhtin** [comment]
How I can install the latest version plugin with this changes?

**Comment by shyim** [comment]
@evgenii-rekhtin you have to wait until JetBrains has approved the update in the store.

**Pull request merged**
